export type InsuranceProductStatus = "ACTIVE" | "INACTIVE";
export type InsuranceCategory = "ALL" | "LOSS_THEFT" | "MEDICAL" | "FLIGHT" | "LONG_TRIP";
export type PartnerInsuranceProduct = {
  id: string;
  insurerName: string;
  productName: string;
  logoAsset?: string;
  detailUrl?: string;
  status: InsuranceProductStatus;
  disclosureLabel: string;
  priceLabel?: string;
  features?: string[];
  recommendationReason?: string;
  recommended?: boolean;
  recommendationTarget?: string;
  coverageExamples?: string[];
  categories?: Exclude<InsuranceCategory, "ALL">[];
  caution?: string;
};
export type InsuranceProductsOverview = { products: PartnerInsuranceProduct[]; updatedAt?: string };
export type InsuranceProductsNavigationTarget = { source: "S06_DOCUMENTS" };
