import { Ionicons } from "@expo/vector-icons";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { CaseBottomNavigation } from "@/features/documents/components/CaseBottomNavigation";
import { colors, radius, spacing } from "@/theme/tokens";
import type { InsuranceProductsViewProps } from "./InsuranceProductsView.types";

export function InsuranceProductsViewShared(props: InsuranceProductsViewProps) {
  const canOpen = Boolean(props.selectedProductId) && !props.isLoading;
  return <SafeAreaView style={styles.safeArea}>
    <View style={styles.header}><Pressable accessibilityLabel="보험상품 안내에서 뒤로가기" accessibilityRole="button" onPress={props.onBack} style={styles.headerButton}><Ionicons accessibilityElementsHidden color={colors.primary} name="arrow-back" size={25} /></Pressable><Text accessibilityRole="header" style={styles.headerTitle}>Ansim Travel</Text><View style={styles.headerButton}><Ionicons accessibilityElementsHidden color={colors.primary} name="person-circle-outline" size={24} /></View></View>
    <ScrollView contentContainerStyle={styles.content}>
      <Text accessibilityRole="header" style={styles.title}>가입하신 보험이 있나요?</Text>
      <Text style={styles.description}>정확한 맞춤형 안내를 위해 보험 정보를 선택해 주세요.</Text>
      <View accessibilityLabel="제휴 보험상품 안내" style={styles.notice}><Ionicons accessibilityElementsHidden color={colors.primary} name="information-circle-outline" size={22} /><Text style={styles.noticeText}>여행 중 사건이 발생하면 여행자보험을 통해 일정 부분 보상받을 수 있습니다. 제휴 보험상품을 확인해 보세요.</Text></View>
      <View style={styles.toggleCard}><View><Text style={styles.toggleTitle}>여행자보험 가입 여부</Text><Text style={styles.toggleDescription}>출국 전 여행자보험에 가입하셨나요?</Text></View><Switch accessibilityLabel="여행자보험 가입 여부" onValueChange={props.onToggleInsurance} value={props.hasTravelInsurance} /></View>
      <Text accessibilityRole="header" style={styles.sectionTitle}>보험사 선택</Text>
      {props.isLoading ? <View accessibilityLabel="보험상품 정보를 준비하고 있습니다" style={styles.stateCard}><Text>보험상품 정보를 준비하고 있습니다.</Text></View> : props.errorMessage ? <View accessibilityRole="alert" style={styles.stateCard}><Text style={styles.errorText}>{props.errorMessage}</Text></View> : props.products.length === 0 ? <View style={styles.stateCard}><Text>현재 안내할 수 있는 제휴 보험상품이 없습니다.</Text></View> : <View style={styles.grid}>{props.products.map((product) => { const selected = product.id === props.selectedProductId; return <Pressable key={product.id} accessibilityLabel={`${product.insurerName} ${product.productName}`} accessibilityRole="button" accessibilityState={{ selected }} onPress={() => props.onSelectProduct(product.id)} style={[styles.productCard, selected && styles.selectedCard]}><View style={styles.logoPlaceholder}><Ionicons accessibilityElementsHidden color={colors.primary} name="shield-checkmark-outline" size={25} /></View><Text style={styles.insurerName}>{product.insurerName}</Text><Text style={styles.productName}>{product.productName}</Text><Text style={styles.disclosure}>{product.disclosureLabel}</Text></Pressable>; })}</View>}
      <Pressable accessibilityHint="선택한 제휴 보험상품 상세를 엽니다." accessibilityLabel="제휴 상품 보기" accessibilityRole="button" accessibilityState={{ disabled: !canOpen }} disabled={!canOpen} onPress={props.onOpenProduct} style={({ pressed }) => [styles.primaryButton, !canOpen && styles.disabled, pressed && styles.pressed]}><Text style={styles.primaryText}>제휴 상품 보기</Text><Ionicons accessibilityElementsHidden color={colors.background} name="arrow-forward" size={21} /></Pressable>
      <Text style={styles.disclaimer}>보험 가입 및 보상 조건은 각 보험사 약관을 확인해 주세요.</Text>
    </ScrollView>
    <CaseBottomNavigation activeTab="guide" onCaseTab={props.onCaseTab} onGuideTab={props.onGuideTab} onDocumentsTab={props.onDocumentsTab} />
  </SafeAreaView>;
}

const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.surface }, header: { minHeight: 58, width: "100%", maxWidth: 480, alignSelf: "center", flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md, backgroundColor: colors.background }, headerButton: { width: 40, minHeight: 40, alignItems: "center", justifyContent: "center" }, headerTitle: { color: colors.primary, fontSize: 16, fontWeight: "900" }, content: { width: "100%", maxWidth: 480, alignSelf: "center", padding: spacing.md, paddingBottom: spacing.xl }, title: { marginTop: spacing.md, color: colors.text, fontSize: 24, fontWeight: "900" }, description: { marginTop: spacing.xs, color: colors.textSecondary, fontSize: 14, lineHeight: 21 }, notice: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.lg, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.primarySoft }, noticeText: { flex: 1, color: colors.textSecondary, fontSize: 13, lineHeight: 19 }, toggleCard: { marginTop: spacing.lg, padding: spacing.md, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderRadius: radius.md, backgroundColor: colors.background }, toggleTitle: { color: colors.text, fontSize: 16, fontWeight: "900" }, toggleDescription: { marginTop: spacing.xs, color: colors.textSecondary, fontSize: 12 }, sectionTitle: { marginTop: spacing.lg, marginBottom: spacing.sm, color: colors.text, fontSize: 18, fontWeight: "900" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, productCard: { width: "48%", minHeight: 145, alignItems: "center", justifyContent: "center", padding: spacing.sm, borderWidth: 1, borderColor: colors.background, borderRadius: radius.md, backgroundColor: colors.background }, selectedCard: { borderColor: colors.primary, borderWidth: 2 }, logoPlaceholder: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 22, backgroundColor: colors.primarySoft }, insurerName: { marginTop: spacing.xs, color: colors.text, fontSize: 14, fontWeight: "900" }, productName: { marginTop: 2, color: colors.textSecondary, fontSize: 11 }, disclosure: { marginTop: spacing.xs, color: colors.primary, fontSize: 10, fontWeight: "800" }, stateCard: { padding: spacing.lg, borderRadius: radius.md, backgroundColor: colors.background }, errorText: { color: colors.error }, primaryButton: { minHeight: 56, marginTop: spacing.lg, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm, borderRadius: radius.lg, backgroundColor: colors.primary }, primaryText: { color: colors.background, fontSize: 16, fontWeight: "900" }, disclaimer: { marginTop: spacing.sm, color: colors.textSecondary, fontSize: 11, lineHeight: 17, textAlign: "center" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.75 } });
