const { withAppBuildGradle } = require("expo/config-plugins");

const BLOCK = `
// @generated by withAgoraAudioOnly
configurations.configureEach {
    exclude group: "io.agora.rtc", module: "full-screen-sharing"
}
`;

module.exports = function withAgoraAudioOnly(config) {
  return withAppBuildGradle(config, (nextConfig) => {
    if (!nextConfig.modResults.contents.includes("withAgoraAudioOnly")) {
      nextConfig.modResults.contents += BLOCK;
    }

    return nextConfig;
  });
};
